version: "3.8"

services:
    invoice_app_frontend:
        container_name: Invoice_App_Frontend
        build:
            context: ./invoice-generator-app
            dockerfile: Dockerfile.app
            target: development
        ports:
            - "3000:3000"
        volumes:
            - ./invoice-generator-app:/app

    invoice_backend_server:
        container_name: Invoice_Backend_Server
        build:
            context: ./backend
            dockerfile: Dockerfile.server
        ports:
            - "4000:4000"
